vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /upload/img
            upload_destination: '%kernel.project_dir%/public/upload/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
