<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230823105309 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_composition (id INT AUTO_INCREMENT NOT NULL, recipe_id INT NOT NULL, preparation_id INT NOT NULL, weight NUMERIC(8, 3) NOT NULL, INDEX IDX_D88D0D2359D8A214 (recipe_id), INDEX IDX_D88D0D233DD9B8BA (preparation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE recipe_composition ADD CONSTRAINT FK_D88D0D2359D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id)');
        $this->addSql('ALTER TABLE recipe_composition ADD CONSTRAINT FK_D88D0D233DD9B8BA FOREIGN KEY (preparation_id) REFERENCES preparation (id)');

        $this->addSql("
        INSERT INTO measure_unit (id,name) VALUES(1,'Kg');
INSERT INTO measure_unit (id,name) VALUES(2,'L');
INSERT INTO measure_unit (id,name) VALUES(3,'Unité');

INSERT INTO ingredient (id,code, measure_unit_id) VALUES(6,'Amande blanche batonnet',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(7,'Amande blanche hachée',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(8,'Amandes ',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(9,'Ananas frais',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(10,'Baking',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(11,'Basilic frais',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(12,'Baton boulanger chocolat 44%',3);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(13,'Beurre belge',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(14,'Beurre brioche',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(15,'Beurre lescure AOP 1Kg',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(16,'Beurre surgères 1Kg',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(17,'Blanc d\'œufs',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(18,'Framboise fraiche',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(19,'Brunoise de mangue',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(20,'Cacao poudre',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(21,'Café grain',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(22,'Cassonade',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(23,'Citron',3);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(24,'Champagne',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(25,'Choco amber 32%',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(26,'Choco blanc 34% - belcolade extra',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(27,'Choco blanc 34% - couverture',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(28,'Choco Gianduja',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(29,'Choco lait caramel 35%',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(30,'Choco noir perou 64%',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(31,'Choco noir sanaga 66%',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(32,'Classic Vanille ',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(33,'Colorant argent sucre tiré',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(34,'Colorant Lipo rouge',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(35,'Colorant poudre blanc',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(36,'Colorant poudre Bleu',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(37,'Colorant poudre Bleu indigo',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(38,'Colorant poudre jaune',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(39,'Colorant poudre noir',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(40,'Colorant poudre or',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(41,'Colorant poudre or rubis',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(42,'Colorant poudre orange',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(43,'Colorant poudre rouge fraise',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(44,'Colorant poudre rouge père noel',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(45,'Colorant poudre vert',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(46,'Creme',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(47,'Crème de nougat',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(48,'Crème UHT - 1L',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(49,'Eau d’hydratation',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(50,'Farine patissière',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(51,'Fécule',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(52,'Feuilletine',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(53,'Fleur de sel',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(54,'Fraise fraiche',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(55,'Fromage blanc',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(56,'Gelatine',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(57,'Gelée dessert ',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(58,'Glassage miroir neutre',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(59,'Huile',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(60,'Huile pépin de raisin',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(61,'Huile Tournesol',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(62,'Jaune d\'œufs',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(63,'Jus citron',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(64,'Jus citron vert',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(65,'Lair entier',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(66,'Lait concentré',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(67,'Lait demi écrémé',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(68,'Levure',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(69,'Maizena',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(70,'Miel',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(71,'Nashi',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(72,'Noisette effilée',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(73,'Noisette rapée',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(74,'Œuf',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(75,'Pâte amande catania',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(76,'Pâte cacao Noir 96%',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(77,'pâte noisette',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(78,'Pâte pistache',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(79,'Pectine NH',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(80,'Pectine Pate fruit',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(81,'Pistache bâton',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(82,'Poire',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(83,'Pomme golden',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(84,'Poudre d\'amande',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(85,'Poudre de noisette',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(86,'Pralicrac caramel beurre salé',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(87,'Praliné',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(88,'Purée Ananas',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(89,'Purée Cassis',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(90,'Purée Cerise',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(91,'Purée Clementine corse',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(92,'Purée cocktail caraibe',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(93,'Purée de fruit Framboise',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(94,'Purée Figue',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(95,'Purée Fraise',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(96,'Purée Framboise',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(97,'Purée kalamansi',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(98,'Purée Litchi',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(99,'Purée Mangue',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(100,'Purée Mure',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(101,'Purée Orange',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(102,'Purée Passion',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(103,'Purée Pêche sanguine',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(104,'Purée Rhubarbe',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(105,'Royaltine',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(106,'Sel',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(107,'Sirop glucose',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(108,'Sucre cassonade',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(109,'Sucre glace',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(110,'Sucre inverti',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(111,'Sucre roux',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(112,'Sucre semoule',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(113,'Sucre vergeoise blonde',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(114,'Vanille gousse',3);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(115,'Volcano',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(116,'Yahourt',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(117,'Zeste citron',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(118,'Zeste citron vert',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(119,'Zeste d’orange',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(120,'Basilic surgelés',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(121,'Beurre brioche',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(122,'Rhum',2);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(123,'Fondant patissier',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(124,'Trimoline',1);
INSERT INTO ingredient (id,code, measure_unit_id) VALUES(125,'Choco lait vietnam 45%',1);

INSERT INTO supplier (id,name, updated_at) VALUES(1,'Metro',now());
INSERT INTO supplier (id,name, updated_at) VALUES(2,'Cantrel',now());
INSERT INTO supplier (id,name, updated_at) VALUES(3,'Puratos',now());

INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(2,2,6,6.600,'AMANDES BL BATONNET - 1 KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(3,2,12,0.020,'BATON BOUL. 44% BTE 300 **BARRY**',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(4,2,15,11.200,'BEURRE DOUX PLQ 1KG LESCURE AOP',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(5,2,14,6.300,'Beurre lingot CAROTENE',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(6,2,16,6.300,'Beurre surgères',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(7,2,17,4.000,'BLANC OEUF COCOVITE 1 KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(8,2,21,14.450,'CAFE TRADITION EN GRAIN - 1KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(9,2,35,124.570,'COLOR BLANC 1021 300G',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(10,2,33,115.320,'COLOR EFFET METAL ARGENT SUCRE TIRE  (qte inconnue, probablement 100g)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(11,2,37,345.970,'COLOR LAQUE bleu 100G',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(12,2,40,745.160,'COLOR OR PRECIEUX 25G',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(13,2,39,220.000,'COLOR POUDRE LAQUE NOIR LAQUE 100G CH55',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(14,2,42,256.120,'COLOR POUDRE LAQUE ORANGE 100G',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(15,2,45,171.600,'COLOR POUDRE LAQUE VERT LAQUE 100G',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(16,2,44,195.000,'COLOR POUDRE ROUGE PERE NOEL INT51- 50G',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(17,2,37,663.330,'COLORANT CHOCOLAT PM bleu INDIGO 15 gr',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(18,2,43,663.330,'COLORANT CHOCOLAT PM ROUGE FRAISE 15 gr',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(19,2,38,195.070,'COLORANT LAQUE JAUNE (qte inconnue, probablement 100g)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(20,2,41,405.900,'COLORANT OR RUBIS 30 cc (qte inconnue, probablement 30g)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(21,2,27,2.440,'COUV BAR 34% BLANC ZEPHYR - 5KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(22,2,48,4.700,'CREME UHT LESCURE 35% - 1L',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(23,2,51,2.530,'FECULE POMME DE TERRE PANEMEX - SAC 5KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(24,2,28,15.600,'GIANDUJA PLAISIR LAIT - 2,5 KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(26,2,60,4.400,'HUILE PEPINS RAISIN BIDON 5L',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(27,2,62,7.000,'JAUNE OEUF FRAIS COCOVITE',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(28,2,66,5.120,'LAIT CONCENTRE SUCRE BTE4/4 1KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(29,2,67,0.690,'LAIT UHT 1/2 ECREME X6L',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(30,2,70,16.000,'MIEL CREMEUX POITOU CHARENTES - 1KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(31,2,74,4.200,'OEUF CAISSE 180 GROS CAL 63/73',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(32,2,80,43.640,'Pectine POM.JAUNE PATE FRUIT FRA',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(33,2,79,47.670,'Pectine POMME NH NAPPAGE DGF *',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(34,2,83,1.300,'POMME GOLDEN 70/75 - CAGETTE 10KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(35,2,88,7.030,'PUREE ANANAS BOIRON 100%',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(36,2,89,8.080,'PUREE CASSIS BOIRON 100%',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(37,2,90,8.550,'PUREE CERISE NOIRE N/SUC 100% BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(38,2,92,8.220,'PUREE COCKT CARAIBE RHUM',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(39,2,94,8.140,'PUREE FIGUE BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(40,2,91,11.110,'PUREE IGP CLEMENTINE CORSE 100% BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(41,2,97,8.470,'PUREE KALAMANSI N SUCRE BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(42,2,98,8.470,'PUREE LITCHI SUC 100% BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(43,2,99,8.400,'PUREE MANGUE N/SUC BOIRON 100%*',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(44,2,100,12.140,'PUREE MURES BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(45,2,102,9.650,'PUREE PASSION N/SUC 100% BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(46,2,103,8.280,'PUREE PECHE SANGUINE 100% BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(47,2,104,6.160,'PUREE RHUBARBE NS BOIRON',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(48,2,96,10.300,'PUREE SEAU FRAMBOISE - 10 KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(49,2,105,7.180,'ROYALTINE DGF -BTE 2KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(50,2,106,0.000,'Sel',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(51,2,108,1.950,'SUCRE CASSONADE PURE CANNE - S 5 KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(52,2,109,1.430,'SUCRE GLACE AMYLACE S.10K',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(53,2,112,1.200,'SUCRE SEMOULE PATIS - SAC 25K',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(54,2,113,2.000,'SUCRE VERGEOISE BLONDE - 10 KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(55,2,110,1.980,'TRIMOLINE SUCRE INVERTI SEAU 7KG',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(56,2,120,2.410,'Basilic surgelés',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(57,3,6,8.260,'am blc batonnet',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(58,3,7,7.380,'am blc hachee',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(59,3,84,5.500,'am blc poudre',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(60,3,25,9.530,'BEL AMBER DOUCEUR',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(61,3,20,10.590,'BEL CACAO POUDRE CT 3kg',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(62,3,76,8.140,'BEL EBONY 96',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(63,3,26,7.930,'BEL EXTRA BLANC 34',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(64,3,29,8.160,'BEL LAIT CARAMEL 35',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(65,3,30,11.500,'BEL O N PEROU 64',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(66,3,32,43.330,'classic vanille td 1.1kg',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(67,3,31,10.430,'CT Origins Noir Sanaga 66%',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(68,3,50,1.150,'Farine pâtissiere',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(69,3,56,14.800,'gelatine de boeuf',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(70,3,58,4.200,'glassage neutre s5k',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(71,3,72,12.330,'nois brut eff',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(72,3,85,8.800,'nois brut rap',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(73,3,75,7.620,'p.a catania 50%',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(74,3,48,4.100,'patiscrem creme uht /1l',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(75,3,79,26.500,'Pectine NHnappages',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(76,3,77,12.720,'PF fluide pate noisette 14kg',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(77,3,81,34.510,'pistache verte baton 1kg',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(78,3,86,11.280,'Pralicrac caramel beur sal',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(79,3,107,1.700,'sirop glucose conf/20k',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(80,3,110,1.890,'trimoline sir sucre inv',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(81,3,114,0.693,'vanille gousse 17/20 b250g',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(82,3,115,5.050,'volcano poudre a lever',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(83,1,122,15.000,'Rhum',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(84,1,18,10.000,'Framboise (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(85,1,95,8.300,'Purée fraise (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(86,1,9,4.440,'Ananas frais (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(87,1,54,12.500,'Fraise fraiche (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(88,1,24,12.000,'Champagne (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(89,1,123,3.130,'Fondant pâtissier (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(90,1,116,2.630,'Yahourt (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(91,1,61,4.000,'Huile de tournesol (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(92,1,23,0.330,'Citron unité (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(93,1,10,14.400,'Baking (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(94,1,55,3.550,'Fromage blance (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(95,1,68,6.800,'Levure (prix temporaire)',now());
INSERT INTO supplier_price (id,supplier_id,ingredient_id,price,name,updated_at) VALUES(96,1,49,0.001,'Eau d’hydratation',now());





INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (1,1,67,180.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (2,1,28,420.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (3,1,56,6.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (4,1,48,525.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (5,1,49,36.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (6,2,50,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (7,3,50,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (8,3,14,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (9,3,74,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (10,4,50,310.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (11,4,115,8.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (12,4,84,160.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (13,4,113,140.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (14,4,16,260.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (15,4,53,14.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (17,4,25,333.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (18,4,59,33.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (19,4,86,106.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (22,42,67,430.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (23,42,62,220.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (24,42,112,290.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (25,42,56,18.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (26,42,49,108.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (27,42,48,880.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (28,42,32,50.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (29,42,114,4000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (30,42,106,3.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (31,43,49,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (32,43,67,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (33,43,50,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (34,43,74,800.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (35,43,60,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (36,43,15,400.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (37,43,17,800.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (38,43,112,350.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (39,44,87,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (40,53,12,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (41,44,125,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (42,46,50,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (43,46,68,30.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (44,46,112,72.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (45,46,106,10.800,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (46,46,16,18.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (47,46,15,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (49,47,50,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (50,47,67,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (51,47,112,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (52,47,74,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (53,47,83,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (54,47,122,5.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (55,48,67,750.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (56,48,48,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (57,48,74,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (58,48,62,40.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (59,48,112,210.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (60,48,69,85.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (61,48,32,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (63,49,112,1050.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (64,49,48,240.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (65,49,15,240.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (67,50,48,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (68,50,50,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (69,50,62,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (70,50,112,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (71,50,69,80.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (72,50,31,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (73,51,123,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (74,51,31,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (75,52,48,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (76,52,50,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (77,52,62,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (78,52,112,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (79,52,69,80.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (80,52,114,2000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (81,41,47,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (82,41,125,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (83,40,16,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (84,40,112,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (85,40,84,75.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (86,40,50,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (87,40,17,120.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (88,40,32,70.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (89,39,95,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (90,39,120,18.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (91,39,112,50.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (92,39,54,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (93,38,95,1600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (94,38,110,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (95,38,112,114.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (96,38,79,36.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (97,38,56,18.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (98,37,48,1300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (99,37,112,91.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (101,37,32,50.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (102,37,56,10.500,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (103,36,74,800.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (104,36,84,350.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (105,36,50,180.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (106,36,16,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (107,36,112,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (108,36,17,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (109,36,78,80.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (110,36,109,350.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (111,35,74,80.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (112,35,31,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (113,35,48,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (115,34,52,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (118,34,31,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (121,34,87,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (135,33,62,1080.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (136,33,112,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (137,33,30,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (138,33,76,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (139,33,17,1620.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (140,33,112,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (141,32,63,375.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (142,32,17,210.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (144,32,74,240.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (145,32,112,225.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (146,32,56,6.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (147,32,49,36.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (148,32,16,225.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (149,31,112,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (150,31,49,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (151,31,17,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (152,30,112,2000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (153,30,49,1500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (154,29,31,740.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (155,29,46,360.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (156,29,62,280.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (157,29,46,1200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (158,28,67,510.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (159,28,48,510.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (160,28,62,180.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (161,28,112,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (162,28,31,660.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (163,27,17,850.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (164,27,16,975.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (165,27,31,495.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (166,27,84,1260.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (167,27,109,1260.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (168,27,20,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (169,27,51,32.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (170,27,62,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (171,27,17,870.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (172,27,112,510.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (173,26,50,1250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (174,26,74,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (175,26,20,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (176,26,62,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (177,26,111,850.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (178,26,84,750.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (179,26,16,1400.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (180,26,53,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (181,26,22,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (182,26,16,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (183,25,88,350.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (184,25,102,650.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (185,25,112,80.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (186,25,48,80.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (187,25,9,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (188,23,55,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (189,23,112,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (190,23,56,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (191,23,49,120.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (192,23,48,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (193,22,116,520.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (194,22,112,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (195,22,74,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (196,22,50,1400.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (197,22,61,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (198,22,10,35.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (201,22,23,2000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (202,21,83,4500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (203,21,16,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (204,21,112,900.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (205,21,58,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (206,1,67,180.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (207,1,28,420.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (208,1,56,6.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (209,1,48,525.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (210,1,49,36.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (211,20,15,30.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (212,20,112,40.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (213,20,64,70.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (215,20,19,800.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (216,20,99,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (217,20,102,180.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (218,20,101,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (219,20,56,9.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (220,19,99,560.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (221,19,102,75.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (222,19,112,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (223,19,62,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (224,19,56,11.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (225,19,15,285.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (226,18,74,330.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (227,18,112,360.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (228,18,50,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (229,18,115,8.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (230,18,59,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (231,18,15,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (232,18,67,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (233,18,106,6.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (235,17,74,304.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (236,17,112,330.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (237,17,50,276.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (238,17,115,7.500,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (239,17,59,55.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (240,17,15,276.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (241,17,67,92.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (242,17,106,5.500,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (243,17,32,37.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (244,16,56,36.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (245,16,107,90.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (246,16,112,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (247,16,100,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (248,16,107,135.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (249,15,112,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (250,15,67,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (251,15,107,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (252,15,58,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (253,15,32,50.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (254,15,56,15.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (255,15,25,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (256,14,30,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (257,14,48,635.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (258,13,22,115.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (259,13,15,120.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (260,13,83,900.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (261,13,71,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (262,13,82,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (263,13,112,350.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (264,13,48,160.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (265,13,56,15.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (266,12,48,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (267,12,65,255.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (268,12,62,280.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (269,12,113,280.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (271,12,32,25.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (272,12,57,90.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (273,11,75,900.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (274,11,112,150.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (275,11,62,280.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (276,11,74,140.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (277,11,15,130.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (278,11,17,400.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (279,11,112,160.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (280,11,20,130.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (281,11,50,130.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (282,10,86,900.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (285,9,67,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (286,9,107,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (287,9,56,34.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (288,9,49,180.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (289,9,26,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (290,9,58,1000.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (291,9,43,5.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (292,8,24,432.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (293,8,62,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (294,8,112,345.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (296,8,56,18.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (297,8,49,108.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (298,8,32,16.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (299,8,48,880.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (300,7,96,590.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (301,7,18,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (302,7,32,30.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (303,7,110,170.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (304,7,112,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (305,7,79,20.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (306,7,56,10.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (307,7,49,60.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (308,6,109,500.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (309,6,84,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (310,6,85,250.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (311,6,17,600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (312,6,70,240.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (313,6,81,65.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (314,6,6,65.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (315,6,72,65.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (316,5,62,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (317,5,112,120.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (318,5,15,100.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (319,5,50,200.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (320,5,68,10.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (321,5,53,3.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (323,48,16,25.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (324,24,88,1600.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (325,24,110,300.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (326,24,112,114.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (327,24,79,36.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (329,24,56,18.000,0);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (16,4,119,0,3);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (100,37,114,0,3);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (199,22,63,0,2);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (200,22,117,0,2);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (214,20,114,0,2);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (234,18,118,0,8);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (270,12,114,0,2);
INSERT INTO preparation_ingredient (id,preparation_id,ingredient_id, weight,quantity) VALUES (295,8,119,0,2);


INSERT INTO recipe (id,name,code, is_frame) VALUES (1,'Tarte tatin','TATIN',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (2,'Entremet fromage blanc','ENT_FROMBLANC',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (3,'Choc est là','CHOKELA',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (4,'Entremet citron meringué','ENT_CITME',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (5,'Rocher chocolat','ROCHERCHOC',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (6,'Entremet Amande/Pistache - panacotta','ENT_PISTAMANDE',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (7,'Framboise sur son 31','ENT_FRAMB31',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (8,'Magie exotique','ENT_MAGIEXO',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (9,'Nuage de Vanille','ENT_NUAGE',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (10,'Entremet Tatin Satin','ENT_TATSAT',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (11,'Tablette guimauve','TAB_GUIMAUVE',0);
INSERT INTO recipe (id,name,code, is_frame) VALUES (12,'Tablette madeleine','TAB_MADE',0);
INSERT INTO recipe (id,name,code, is_frame) VALUES (13,'Clafoutis Pommes','CLAFPOM',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (14,'Flan','FLAN',1);
INSERT INTO recipe (id,name,code, is_frame) VALUES (15,'Eclair Chocolat 80g','ECLAIRCHOC80',0);

INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (3,1,3,700.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (4,1,21,6000.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (5,2,22,1800.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (6,2,23,3000.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (7,3,26,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (8,3,27,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (9,3,28,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (10,3,29,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (11,3,30,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (12,4,5,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (13,4,31,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (14,4,32,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (16,5,33,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (17,5,34,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (18,5,35,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (19,6,36,1800.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (20,6,37,3000.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (21,7,4,900.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (22,7,6,1800.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (23,7,7,2200.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (24,7,8,2000.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (25,8,18,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (26,8,19,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (27,8,20,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (28,8,1,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (29,9,40,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (30,9,41,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (31,9,37,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (32,9,42,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (33,10,34,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (34,10,11,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (35,10,12,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (36,10,13,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (37,10,14,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (38,10,15,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (39,11,16,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (40,12,17,1.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (41,13,47,4600.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (42,14,48,5500.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (43,14,3,1300.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (44,15,43,14.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (45,15,50,60.000);
INSERT INTO recipe_composition (id,recipe_id,preparation_id, weight) VALUES (46,15,51,6.000);

");

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_composition DROP FOREIGN KEY FK_D88D0D2359D8A214');
        $this->addSql('ALTER TABLE recipe_composition DROP FOREIGN KEY FK_D88D0D233DD9B8BA');
        $this->addSql('DROP TABLE recipe_composition');
    }
}
